# Generated by Django 5.2.14 on 2026-05-27 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "ingrediente",
                "verbose_name_plural": "ingredientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("descripcion", models.TextField()),
                ("instrucciones", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="recetas/"),
                ),
                (
                    "tiempo_preparacion",
                    models.PositiveIntegerField(
                        help_text="Tiempo de preparación en minutos"
                    ),
                ),
                (
                    "tiempo_coccion",
                    models.PositiveIntegerField(
                        help_text="Tiempo de cocción en minutos"
                    ),
                ),
                ("porciones", models.PositiveIntegerField(default=4)),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("facil", "Facil"),
                            ("media", "Media"),
                            ("dificil", "Dificil"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("publicado", models.BooleanField(default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recetas",
                        to="recetas.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "receta",
                "verbose_name_plural": "recetas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="RecetaIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("g", "Gramos"),
                            ("kg", "Kilogramos"),
                            ("ml", "Mililitros"),
                            ("l", "Litros"),
                            ("tsp", "Cucharadita"),
                            ("tbsp", "Cucharada"),
                            ("taza", "Taza"),
                            ("unidad", "Unidad"),
                            ("al_gusto", "Al gusto"),
                        ],
                        default="unidad",
                        max_length=20,
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True,
                        help_text="Ej: picado fino, a temperatura ambiente",
                        max_length=200,
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="recetas.ingrediente",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receta_ingredientes",
                        to="recetas.receta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente de receta",
                "verbose_name_plural": "Ingredientes de receta",
                "unique_together": {("receta", "ingrediente")},
            },
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="recetas.receta",
                    ),
                ),
            ],
            options={
                "verbose_name": "valoracion",
                "verbose_name_plural": "valoraciones",
                "ordering": ["-creado_en"],
                "unique_together": {("receta", "autor")},
            },
        ),
    ]
