# Generated by Django 5.2.14 on 2026-05-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recetas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="valoracion",
            old_name="puntuacion",
            new_name="valoracion",
        ),
        migrations.AlterField(
            model_name="receta",
            name="publicado",
            field=models.BooleanField(default=True),
        ),
    ]
