# Generated by Django 5.2.10 on 2026-06-02 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recetas", "0002_rename_puntuacion_valoracion_valoracion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True,
                related_name="recetas_favoritas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
